language: ruby
rvm:
  - 2.2
  - jruby

services:
  - mysql

before_install:
  - if [[ `ruby -v` != 2.2 ]]; then
      rvm install ruby-2.2;
      rvm use 2.2 --default;
    fi
  - ruby --version

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

gemfile:
  - Gemfile

script:
  - bin/bundle install
  - ./scripts/initialize-database.sh
  - bin/bundle exec rspec

notifications:
  email: false
