language: ruby
rvm:
  - 2.2.6
  - jruby

services:
  - mysql

before_install:
  - if [[ `ruby -v` != 2.2.6 ]]; then
      rvm install ruby-2.2.6;
      rvm use 2.2.6 --default;
    fi
  - ruby --version

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - gem install bundler

gemfile:
  - Gemfile

script:
  - bin/bundle install
  - ./scripts/initialize-database.sh
  - bin/rails db:drop db:create db:migrate
  - bin/bundle exec rspec

notifications:
  email: false
